### ISSUE TITLE
Define plugin options in external file

### ISSUE THREAD

**Issue by levithomason** [chmontgomery/gulp-help#29]
When splitting a gulpfile into multiple task files you require gulp many times.  It'd be useful to be able to define the help options in package.json or some other config.  I realize one could do something like:

```js
var gulp = require('gulp-help')(require('gulp'), require('.gulphelp.json'));
```

It'd be nice if this were inferred automatically from a dot file or package.json.

**Comment by chmontgomery** [comment]
An interesting idea. The problem would be we'd be adding the overhead of a file exists/load (via `require` or `fs`) to each gulp invocation. I've been trying to keep `gulp-help` fast so we don't slow down people's gulp tasks unnecessarily. Considering the simple work-around you outlined above, I don't think the overhead is worth the typical use case.

Also, you can simplify your workaround even more by putting the whole line in an external file, e.g.:

```js
// gulp-custom.js
module.exports = require('gulp-help')(require('gulp'), require('.gulphelp.json'));
```

```js
// gulpfile.js
var gulp = require('./gulp-custom.js');
```

**Comment by levithomason** [comment]
Using package.json may solve the issue you raised as it is probably safe to assume there is a package.json if you're using gulp-help.  None the less, the workaround is less code for the world to maintain and working well.  Thanks.
