### ISSUE TITLE
Add option to hide tasks without help message

### ISSUE THREAD

**Issue by jessethegame** [chmontgomery/gulp-help#8]
It would be nice to have a boolean option, say, `hideEmpty` to hide tasks that have no help text.

My use case involves a bunch of modular tasks that are included from other files that don't want to know about the `gulpHelp` wrapper. I define an interface with a few documented tasks which are the only ones I intend to show. So, I wish to hide all tasks that are defined without the extra parameter.

A default value of `false` for `hideEmpty` would retain backward compatibility.

Would you be interested in a pull request?

**Comment by chmontgomery** [comment]
@jessethegame sorry, I know I'm a little late to the "game", but I've finally added this feature. If you're still using `gulp-help`, please try it out: `v1.6.0`. Thanks!
